version: '3'

services:
  dns-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns-web
    volumes:
      - ./dns-web/conf:/etc/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=UTC
    networks:
      - proxy

  downloader:
    image: nginx:latest
    container_name: lmsupporttools
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=lmsupporttools.com
    command: /bin/bash -c "apt-get update && apt-get install -y wget && wget https://raw.githubusercontent.com/CosmoSimio/lmsupporttools/master/html/index.html -O /usr/share/nginx/html/index.html && wget https://raw.githubusercontent.com/CosmoSimio/lmsupporttools/master/html/abcgcalculator.html -O /usr/share/nginx/html/abcgcalculator.html && wget https://raw.githubusercontent.com/CosmoSimio/lmsupporttools/master/html/dynamicthresholdscalculator.html -O /usr/share/nginx/html/dynamicthresholdscalculator.html && chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html && nginx -g 'daemon off;'"
    networks:
      - proxy

networks:
  proxy: